### PR TITLE
Fixes regarding Blue Pill implementation

### PR DESCRIPTION
**Pull request by andriandreo**
Hello Maya, 

I learned a lot with your Bare-Metal Programming Guides in *Hackaday*, they are really great. Along this learning path, I was trying to implement different examples for the Blue Pill and faced a few 'bugs' in the libraries needed to properly set up the MCU (mainly regarding `adc`, `gpio`, and `i2c`). 

Please, feel free to check these changes and merge them with your repository if desired.

### CODE REVIEW

**Comment by MayaPosch** [comment]
Thank you for the PR, and glad to hear you like the article series :)

I had a quick look at the commits, and I have two remarks:

* Defining the array size in an external definition is not needed since the size is not used during compile time.
* I'm a bit unclear on the STM32F103 AF changes, could you briefly summarize these?

Thanks! :)

**Comment by andriandreo** [comment]
Hi Maya!

Here are my points: 

- I thought the same, and the compiler prompted no error when compiling the basic examples using GPIO. But whenever I tried to use the USART, the compilation just did not succeed. I started to debug and I faced that those array sizes were indeed defined for the rest of the boards but not for the Blue Pill. Not until I proceeded with the definition did the compilation work. 
- Regarding the AF changes: I am afraid that your initial external definitions regarding the USART ports were wrong considering the Reference Manual. Namely, you always used the USART1 for the Blue Pill but in ports B6 and B7 with `AF = 0`, however those are the remapped ports therefore `AF` should be equal to `1`. I just rearranged `USART1` to `USART3` to the right ports and AF values (and made sure that the `set_af` function regarding GPIO was triggered as it should).

Thanks to you :)

**Comment by MayaPosch** [comment]
I see, that's an interesting finding. I'll have a gander at it myself to see what's going on there. Thanks for giving things a try there :)

As for the AF changes, it would seem I made a mistake there... I haven't used the STM32F103 a lot yet for development so far, which is probably why. Thanks for debugging it! :)

**Comment by andriandreo** [comment]
Thanks to you for all the hard work here!

I'm glad I could help a bit here :)

**Pull request merged**
